### PR TITLE
added apache-v2 license

### PR DESCRIPTION
**Pull request by JohnMurray**

### CODE REVIEW

**Comment by JohnMurray** [comment]
I'd really like to use this code and improve upon it, but the lack of licensing is stopping me here.

**Comment by dgryski** [comment]
I normally use MIT.  Is that OK for your needs?

**Comment by JohnMurray** [comment]
Yeah, MIT works for me. I was just adding something if you didn't care. Let me update the PR.

**Comment by JohnMurray** [comment]
@dgryski  updated

**Pull request merged**
